// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEWRG3nYv_iX87UrUiIiv8zu6q2NFwSA',
    appId: '1:145612880895:web:6303f4eeb3f8c7fbed05ca',
    messagingSenderId: '145612880895',
    projectId: 'jackerbox-8fd7c',
    authDomain: 'jackerbox-8fd7c.firebaseapp.com',
    storageBucket: 'jackerbox-8fd7c.firebasestorage.app',
    measurementId: 'G-HXMTF3KWTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mpCvc2L8vJkrL5RqWzbF_IxNPjJJVhQ',
    appId: '1:145612880895:android:157e284b93234899ed05ca',
    messagingSenderId: '145612880895',
    projectId: 'jackerbox-8fd7c',
    storageBucket: 'jackerbox-8fd7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnHn6VRBHNXGOhO3INkPnEK3vJsU9RzI0',
    appId: '1:145612880895:ios:f54b228f45e7f1bbed05ca',
    messagingSenderId: '145612880895',
    projectId: 'jackerbox-8fd7c',
    storageBucket: 'jackerbox-8fd7c.firebasestorage.app',
    iosClientId: '145612880895-67860pf1hip7n7hljmctnotsv072g9ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.jackerbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnHn6VRBHNXGOhO3INkPnEK3vJsU9RzI0',
    appId: '1:145612880895:ios:f54b228f45e7f1bbed05ca',
    messagingSenderId: '145612880895',
    projectId: 'jackerbox-8fd7c',
    storageBucket: 'jackerbox-8fd7c.firebasestorage.app',
    iosClientId: '145612880895-67860pf1hip7n7hljmctnotsv072g9ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.jackerbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJEWRG3nYv_iX87UrUiIiv8zu6q2NFwSA',
    appId: '1:145612880895:web:edaf1fd3f6d10a6ded05ca',
    messagingSenderId: '145612880895',
    projectId: 'jackerbox-8fd7c',
    authDomain: 'jackerbox-8fd7c.firebaseapp.com',
    storageBucket: 'jackerbox-8fd7c.firebasestorage.app',
    measurementId: 'G-HHCNCDB2B6',
  );

}